# Auth Service Helm Values for Production Environment
replicaCount: 3

image:
  repository: ghcr.io/nmbuild/fintrax-auth-service
  tag: stable
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000
  targetPort: 3000

env:
  - name: NODE_ENV
    value: "production"
  - name: PORT
    value: "3000"
  - name: LOG_LEVEL
    value: "warn"

secrets:
  CLERK_PUBLISHABLE_KEY: "pk_prod_replace_with_prod_key"
  CLERK_SECRET_KEY: "sk_prod_replace_with_prod_key"
  DATABASE_URL: "postgresql://fintraxuser_prod:prodpassword@postgres:5432/fintrax_prod"

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

nodeSelector: {}

tolerations: []

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - auth-service
        topologyKey: kubernetes.io/hostname

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
