services:
  auth-service:
    build: ./services/auth-service
    env_file: ./services/auth-service/.env
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    env_file: ./frontend/.env.local
    ports:
      - "3000:3000"
