apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: fintrax-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: <your-frontend-image>
          ports:
            - containerPort: 3000
