apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: fintrax-dev
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: frontend
          image: ghcr.io/nmbuild/fintrax-frontend:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "development"
            - name: NEXT_PUBLIC_API_URL
              value: "http://auth-service.fintrax-dev.svc.cluster.local:3000"
            - name: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
              value: "pk_test_YWxlcnQtY2FyaWJvdS03MS5jbGVyay5hY2NvdW50cy5kZXYk"
            - name: NEXT_PUBLIC_CLERK_SIGN_IN_URL
              value: "/sign-in"
            - name: NEXT_PUBLIC_CLERK_SIGN_UP_URL
              value: "/sign-up"
            - name: NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL
              value: "/"
            - name: NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL
              value: "/"
          envFrom:
            - secretRef:
                name: frontend-secrets
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
