apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- frontend-deployment.yaml
- frontend-service.yaml
- auth-service-deployment.yaml
- auth-service-service.yaml
- ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: fintrax
  app.kubernetes.io/managed-by: argocd
