apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: fintrax-dev
  labels:
    app: auth-service
    environment: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: ghcr.io/nmbuild/fintrax-auth-service:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "development"
        - name: PORT
          value: "3000"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: fintrax-secrets
              key: database-url
        - name: CLERK_PUBLISHABLE_KEY
          valueFrom:
            secretKeyRef:
              name: fintrax-secrets
              key: clerk-publishable-key
        - name: CLERK_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: fintrax-secrets
              key: clerk-secret-key
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: fintrax-dev
spec:
  selector:
    app: auth-service
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  type: ClusterIP
