apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: fintrax-dev
  labels:
    app: frontend
    environment: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/nmbuild/fintrax-frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "development"
        - name: NEXT_PUBLIC_API_URL
          value: "http://auth-service"
        - name: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
          valueFrom:
            secretKeyRef:
              name: fintrax-secrets
              key: clerk-publishable-key
        - name: CLERK_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: fintrax-secrets
              key: clerk-secret-key
        - name: NEXT_PUBLIC_CLERK_SIGN_IN_URL
          value: "/sign-in"
        - name: NEXT_PUBLIC_CLERK_SIGN_UP_URL
          value: "/sign-up"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: fintrax-dev
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  type: ClusterIP
