apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: fintrax-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: <your-auth-service-image>
          ports:
            - containerPort: 3000
