# Frontend Helm Values for Staging Environment
replicaCount: 2

image:
  repository: ghcr.io/nmbuild/fintrax-frontend
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000
  targetPort: 3000

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - host: fintrax-staging.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

env:
  - name: NODE_ENV
    value: "staging"
  - name: NEXT_PUBLIC_API_URL
    value: "http://auth-service.fintrax-staging.svc.cluster.local:3000"

resources:
  limits:
    cpu: 750m
    memory: 768Mi
  requests:
    cpu: 375m
    memory: 384Mi

nodeSelector: {}

tolerations: []

affinity: {}

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
