replicaCount: 1

image:
  repository: ghcr.io/nmbuild/fintrax-frontend
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

resources: {}

nameOverride: ""
fullnameOverride: ""
