apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fintrax-prod

resources:
- ../../base

images:
- name: ghcr.io/nmbuild/fintrax-frontend
  newTag: latest
- name: ghcr.io/nmbuild/fintrax-auth-service
  newTag: latest

patches:
- path: prod-patches.yaml
- path: security-hardening.yaml
- path: resource-limits.yaml

secretGenerator:
- name: frontend-secrets
  literals:
  - CLERK_SECRET_KEY=${{ secrets.CLERK_SECRET_KEY }}  # Production keys

configMapGenerator:
- name: environment-config
  literals:
  - ENVIRONMENT=production
  - LOG_LEVEL=error
  - DEBUG=false
  - METRICS_ENABLED=true
