name: Auth Service CI

on:
  push:
    paths:
      - 'services/auth-service/**'
      - '.github/workflows/ci-auth-service.yml'
    branches:
      - main
      - develop
      - staging
  pull_request:
    paths:
      - 'services/auth-service/**'
      - '.github/workflows/ci-auth-service.yml'
    branches:
      - main
      - develop
      - staging

permissions:
  contents: write
  packages: write
  actions: read

jobs:
  call-template:
    uses: ./.github/workflows/ci-template.yml
    with:
      service: auth-service