# .github/workflows/ci-frontend.yml
name: CI – Frontend

on:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/ci-frontend.yml'
  pull_request:
    paths:
      - 'frontend/**'

jobs:
  call-ci:
    uses: ./.github/workflows/ci-template.yml
    with:
      service: 'frontend'
      path: 'frontend'
      node-version: '22'
      container: true
