name: Frontend CI

on:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/ci-frontend.yml'
    branches:
      - main
      - develop
      - staging
  pull_request:
    paths:
      - 'frontend/**'
      - '.github/workflows/ci-frontend.yml'
    branches:
      - main
      - develop
      - staging

permissions:
  contents: write
  packages: write
  actions: read

jobs:
  call-template:
    uses: ./.github/workflows/ci-template.yml
    with:
      service: frontend