name: Service CI Template

on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string

jobs:
  lint-test-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: |
          if [ "${{ inputs.service }}" = "frontend" ]; then cd frontend; else cd services/${{ inputs.service }}; fi
          yarn install --frozen-lockfile
      - name: Lint
        run: |
          if [ "${{ inputs.service }}" = "frontend" ]; then cd frontend; else cd services/${{ inputs.service }}; fi
          yarn lint || true
      - name: Test
        run: |
          if [ "${{ inputs.service }}" = "frontend" ]; then cd frontend; else cd services/${{ inputs.service }}; fi
          yarn test || true
      - name: Audit
        run: |
          if [ "${{ inputs.service }}" = "frontend" ]; then cd frontend; else cd services/${{ inputs.service }}; fi
          yarn audit --level high || true
      - name: Set image tag
        id: vars
        run: echo "TAG=${GITHUB_SHA}" >> $GITHUB_ENV
      - name: Build Docker image
        run: |
          if [ "${{ inputs.service }}" = "frontend" ]; then \
            docker build -t ghcr.io/nmbuild/fintrax-frontend:${TAG} ./frontend; \
          else \
            docker build -t ghcr.io/nmbuild/fintrax-${{ inputs.service }}:${TAG} ./services/${{ inputs.service }}; \
          fi
      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Push Docker image
        run: |
          if [ "${{ inputs.service }}" = "frontend" ]; then \
            docker push ghcr.io/nmbuild/fintrax-frontend:${TAG}; \
          else \
            docker push ghcr.io/nmbuild/fintrax-${{ inputs.service }}:${TAG}; \
          fi
      - name: Update deployment manifest with new image tag
        run: |
          if [ "${{ inputs.service }}" = "frontend" ]; then \
            yq e '.spec.template.spec.containers[0].image = "ghcr.io/nmbuild/fintrax-frontend:'"${TAG}"'"' -i infra/k8s/dev/frontend/deployment.yaml; \
            yq e '.spec.template.spec.containers[0].image = "ghcr.io/nmbuild/fintrax-frontend:'"${TAG}"'"' -i infra/k8s/staging/frontend/deployment.yaml; \
            yq e '.spec.template.spec.containers[0].image = "ghcr.io/nmbuild/fintrax-frontend:'"${TAG}"'"' -i infra/k8s/prod/frontend/deployment.yaml; \
          else \
            yq e '.spec.template.spec.containers[0].image = "ghcr.io/nmbuild/fintrax-'"${{ inputs.service }}"':'"${TAG}"'"' -i infra/k8s/dev/${{ inputs.service }}/deployment.yaml; \
            yq e '.spec.template.spec.containers[0].image = "ghcr.io/nmbuild/fintrax-'"${{ inputs.service }}"':'"${TAG}"'"' -i infra/k8s/staging/${{ inputs.service }}/deployment.yaml; \
            yq e '.spec.template.spec.containers[0].image = "ghcr.io/nmbuild/fintrax-'"${{ inputs.service }}"':'"${TAG}"'"' -i infra/k8s/prod/${{ inputs.service }}/deployment.yaml; \
          fi
      - name: Commit and push manifest
        run: |
          git config --global user.email "ci@github.com"
          git config --global user.name "GitHub Actions"
          git add infra/k8s/*/${{ inputs.service }}/deployment.yaml || git add infra/k8s/*/frontend/deployment.yaml
          git commit -m "Update ${{ inputs.service }} image to ${TAG} [ci skip]" || echo "No changes to commit"
          git push
