on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string
      path:
        required: true
        type: string
      node-version:
        required: true
        type: string
      container:
        required: false
        type: boolean
        default: false
      next_public_api_url:
        required: false
        type: string
    # ← Declare any secrets you want callers to pass in
    secrets:
      clerk_publishable_key:
        description: 'Clerk publishable key (frontend only)'
        required: false

jobs:
  # … your lint-test-audit job here …

  container-scan:
    needs: lint-test-audit
    runs-on: ubuntu-latest
    if: ${{ inputs.container }}
    steps:
      - uses: actions/checkout@v4

      # Frontend build (uses the secret)
      - name: Build frontend image (with build-args)
        if: ${{ inputs.service == 'frontend' }}
        uses: docker/build-push-action@v4
        with:
          context: ${{ inputs.path }}
          tags: ${{ inputs.service }}:ci
          load: true
          build-args: |
            NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${{ secrets.clerk_publishable_key }}
            NEXT_PUBLIC_API_URL=${{ inputs.next_public_api_url }}

      # Other services (no build-args)
      - name: Build service image (no build-args)
        if: ${{ inputs.service != 'frontend' }}
        uses: docker/build-push-action@v4
        with:
          context: ${{ inputs.path }}
          tags: ${{ inputs.service }}:ci
          load: true

      - name: Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ inputs.service }}:ci
