name: Destroy AWS Infra

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Terraform environment to destroy (dev, staging, prod)'
        required: true
        default: 'dev'

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6
      - name: Terraform Init
        working-directory: infra/terraform
        run: terraform init
      - name: Terraform Destroy
        working-directory: infra/terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          terraform destroy -auto-approve -var-file=${{ github.event.inputs.environment }}.tfvars
